defmodule Mix.Tasks.TinyCi.Gen.Action do
  @shortdoc "Scaffolds a new TinyCI.Action module and a test stub"

  @moduledoc """
  Generates a module implementing the `TinyCI.Action` behaviour, plus a passing
  ExUnit test stub.

  ## Usage

      mix tiny_ci.gen.action MyApp.Deploy

  Generates:

    * `lib/my_app/deploy.ex` — a compiling module that `use`s `TinyCI.Action`,
      implements `execute/2` (returns `:ok`), and declares `metadata/0`.
    * `test/my_app/deploy_test.exs` — a passing test stub exercising the action.

  Edit `execute/2` to do real work and refine `metadata/0` (name, version,
  inputs, capabilities) to match.
  """

  use Mix.Task

  @impl Mix.Task
  def run(args) do
    module = parse_module!(args)
    create_module_file(module)
    create_test_file(module)
    :ok
  end

  @doc """
  Returns the `lib/` source path for an action `module` name.

  ## Examples

      iex> Mix.Tasks.TinyCi.Gen.Action.module_path("MyApp.Deploy")
      "lib/my_app/deploy.ex"
  """
  @spec module_path(String.t()) :: String.t()
  def module_path(module), do: Path.join("lib", "#{underscore_path(module)}.ex")

  @doc """
  Returns the `test/` path for an action `module` name.

  ## Examples

      iex> Mix.Tasks.TinyCi.Gen.Action.test_path("MyApp.Deploy")
      "test/my_app/deploy_test.exs"
  """
  @spec test_path(String.t()) :: String.t()
  def test_path(module), do: Path.join("test", "#{underscore_path(module)}_test.exs")

  defp parse_module!([module | _]) when is_binary(module), do: module

  defp parse_module!(_) do
    Mix.raise("Expected a module name, e.g. `mix tiny_ci.gen.action MyApp.Deploy`")
  end

  defp underscore_path(module) do
    module
    |> String.split(".")
    |> Enum.map_join("/", &Macro.underscore/1)
  end

  defp create_module_file(module) do
    path = module_path(module)
    Mix.Generator.create_file(path, module_template(module))
  end

  defp create_test_file(module) do
    path = test_path(module)
    Mix.Generator.create_file(path, test_template(module))
  end

  defp metadata_name(module), do: underscore_path(module) |> String.replace("/", ".")

  defp module_template(module) do
    """
    defmodule #{module} do
      @moduledoc \"\"\"
      A TinyCI action. Generated by `mix tiny_ci.gen.action`.
      \"\"\"

      use TinyCI.Action

      alias TinyCI.Action.Metadata

      @impl TinyCI.Action
      def execute(config, ctx) do
        _ = config
        _ = ctx
        :ok
      end

      @impl TinyCI.Action
      def metadata do
        %Metadata{
          name: "#{metadata_name(module)}",
          version: "0.1.0",
          inputs: [],
          capabilities: []
        }
      end
    end
    """
  end

  defp test_template(module) do
    alias_name = module |> String.split(".") |> List.last()

    """
    defmodule #{module}Test do
      use ExUnit.Case, async: true

      alias #{module}

      describe "execute/2" do
        test "returns :ok" do
          assert #{alias_name}.execute([], %TinyCI.Context{}) == :ok
        end
      end

      describe "metadata/0" do
        test "declares a name and version" do
          assert %TinyCI.Action.Metadata{name: name, version: version} = #{alias_name}.metadata()
          assert is_binary(name)
          assert is_binary(version)
        end
      end
    end
    """
  end
end
